title: Test Department
description: A template site for Purdue testing
baseurl: "" # leave empty unless your site is in a subfolder
url: "https://lrbudreau.github.io" # your GitHub Pages URL
theme: minima # optional – only if using a prebuilt theme

# Include folders/files that Jekyll doesn’t process by default
include:
  - _includes
  - _layouts
  - assets

markdown: kramdown
